version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: deployment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
